### ISSUE TITLE
topa00-sp

### ISSUE THREAD

**Issue by anatopor** [nvbach91/4IZ278-2021-2022-LS#117]
# Sweet Home Bakery
Internetový obchod pro vytváření online objednávek v pekárně

## Funkcionalita

- Uživatel bude moci prohlédnout všechny produkty na webu, bude mít možnost nejen prohlížet produkty na hlavní stránce, ale také je filtrovat podle typu. 
- Při prohlížení konkrétního produktu bude mít uživatel možnost přidat produkt do košíku a pokračovat v nákupu, nebo přidat a ihned přejít do košíku. 
- Uživatel bude také moci upravovat položky v nákupním košíku. 
- Pro vytváření objednávek si uživatel musí vytvořit nový účet nebo se přihlasit k svému stávajícímu účtu. 
- Veškeré údaje o uživateli, produktech, stavu košíku a objednávek budou uloženy v databázi.

## Technologie

- Back end - PHP a mySQL
- Front end - JS, SCC a HTML

## Usecase diagram
![UseCase Diagram](https://user-images.githubusercontent.com/99955048/169691970-fa19de0e-b48f-4a7b-ac71-d4ccdadb8b06.svg)

## Návrh databáze

![Logical](https://user-images.githubusercontent.com/99955048/169658534-5c3cdb7b-5c22-4c21-8ebc-37849b58139e.svg)
![Relational](https://user-images.githubusercontent.com/99955048/169658542-dfb8cda4-9232-425b-b962-b40ef1b86b8e.svg)

### Login

![4-Login](https://user-images.githubusercontent.com/99955048/166158687-648dfdcf-7200-4a66-bb46-917a552ebbee.png)

### Sign Up

![5-Sign-Up](https://user-images.githubusercontent.com/99955048/166158722-575ea977-faf2-4dca-a425-a4a663327890.png)

### Homepage

![1-Homepage](https://user-images.githubusercontent.com/99955048/166158728-383a44ba-2a24-4dcc-987a-cbf6251552ea.png)

### Product

![3-Product](https://user-images.githubusercontent.com/99955048/166158739-046f8b2f-dc41-4c2c-9567-26a4e9c4c925.png)

### Cart 

![Cart](https://user-images.githubusercontent.com/99955048/166161128-5fef282d-cf1c-439e-a161-504a34913661.png)

### Admin home page

![2-Admin-home](https://user-images.githubusercontent.com/99955048/169692858-c40217c9-a408-46c9-bd5d-eb38358eadef.png)

### Admin edit product page

![1-Admin-edit-product](https://user-images.githubusercontent.com/99955048/169692859-55b3cfbb-86b4-4422-b74f-887b2dbc51a8.png)

**Comment by nvbach91** [comment]
Minimalni pocet tabulek je 5, pridejte tam napr kategorie produktu

**Comment by nvbach91** [comment]
@anatopor

**Comment by anatopor** [comment]
Moc se omlouvám za tak pozdní aktualizaci. Přidala jsem nový návrh databáze a zmíněný diagram případu použití.
