### ISSUE TITLE
Obhajoba a závěrečná zkouška

### ISSUE THREAD

**Issue by 0nmus** [nvbach91/4IZ278-2021-2022-LS#139]
Dobrý den,

závěrečná zkouška z webových aplikací mi vychází ve stejný den, jako obhajoba semestrální práce, přičemž obhajoba začíná v 9:15 a test v 10:00. Je, prosím, možné v průběhu obhajoby odejít na test a poté se vrátit?

> Stejně mi to vycházelo i minulý semestr na webových technologiích a nebyl to problém.

**Comment by nvbach91** [comment]
Ano lze, pak se vrátíte a pokračujete v obhajobě

**Comment by 0nmus** [comment]
Super, děkuji.
