### ISSUE TITLE
PHP 8.1 😢 

### ISSUE THREAD

**Issue by marek-mikula** [nvbach91/4IZ278-2021-2022-LS#15]
Dobrý den,

veškerou svou práci jsem dělal v PHP verzi 8.1. Na serveru běží 7.3., co jsem koukal. Hádám, že rovnou mohu zapomenout na to i nadále dělat práci v 8.1.? Jinak 1. cvičení jsem samozřejmě přepsal, aby bylo kompatibilní a já ho tak mohl odevzdat.

Nebo by se s tím dalo něco dělat?

Děkuji za odpověď,
M.

**Comment by nvbach91** [comment]
Nemusí to být nasazený na eso.vse.cz, můžete to nechat hostovat kdekoliv jinde, tím pádem nejste omezen verzí
